# Generated by Django 2.1.2 on 2018-10-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20181003_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contenido',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='Hola', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Hola2', max_length=50),
            preserve_default=False,
        ),
    ]
