# Generated by Django 2.1.2 on 2018-10-06 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0005_auto_20181005_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_like', models.ManyToManyField(to='insta.Post')),
                ('user_like', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
