# Generated by Django 2.1.2 on 2018-10-06 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0006_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_post',
            name='post_like',
        ),
        migrations.RemoveField(
            model_name='like_post',
            name='user_like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='gente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like_post',
        ),
    ]
